
services:
  comandaplus-api:
    build: 
      context: .
      dockerfile: Dockerfile
   
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - './appsettings.json/app/appsettings.json'   
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: 'postgres:16-alpine'
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./db-data/:/var/lib/postgresql/data:z   
    networks:
      - postgres-network


networks: 
  postgres-network:
    driver: bridge